version: 2

aliases:
  # -------------------------
  #      ALIASES: Caches
  # -------------------------
  - &restore-deps-cache
    key: deps-cache-{{ checksum "package.json" }}

  - &save-deps-cache
    key: deps-cache-{{ checksum "package.json" }}
    paths:
      - ~/project/node_modules

  # -------------------------
  #  ALIASES: Branch Filters
  # -------------------------
  - &filter-only-master
    branches:
      only: master
  - &filter-only-semantic-pr
    branches:
      only:  /^(pull|fix|feat|dependabot)\/.*$/

defaults: &defaults
  working_directory: ~/project

jobs:

  test:
    <<: *defaults
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache: *restore-deps-cache
      - run: npm install
      - run: npm install codecov
      - run: npm test
      - run: ./node_modules/.bin/codecov
      - save_cache: *save-deps-cache

  windowsbuild:
    <<: *defaults
    docker:
      - image: electronuserland/builder:wine
    steps:
      - checkout
      - run:
          name: "Setup custom environment variables"
          command: |
            echo 'export APP_VERSION_GIT_TAG=$(npm run --silent version)' >> $BASH_ENV # Redirect MY_ENV_VAR into $BASH_ENV
      - run: npm install
      - run: npm run electron:build

  macbuild:
    <<: *defaults
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - run:
          name: "Setup custom environment variables"
          command: |
            echo 'export APP_VERSION_GIT_TAG=$(npm run --silent version)' >> $BASH_ENV # Redirect MY_ENV_VAR into $BASH_ENV
      - run: npm install
      - run: npm run electron:build

  linuxbuild:
    <<: *defaults
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: "Setup custom environment variables"
          command: |
            echo 'export APP_VERSION_GIT_TAG=$(npm run --silent version)' >> $BASH_ENV # Redirect MY_ENV_VAR into $BASH_ENV
      - run: npm install
      - run: npm run electron:build

  release:
    docker:
      - image: circleci/node:10
    steps:
      - run: echo "hello world"

workflows:
  version: 2
  analysis:
    jobs:
      - test:
          filters: *filter-only-semantic-pr
  release:
    jobs:
      - test:
          filters: *filter-only-master
      - windowsbuild:
          filters: *filter-only-master
      - macbuild:
          filters: *filter-only-master
      - linuxbuild:
          filters: *filter-only-master
      - hold:
          filters: *filter-only-master
          type: approval
          requires:
            - test
            - windowsbuild
            - macbuild
            - linuxbuild
      - release:
          filters: *filter-only-master
          requires:
            - hold
